# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
  # ensure_git_branch(branch: 'main')
  # ensure_git_status_clean
  # git_pull
end

platform :ios do
  lane :pod do
    react_native_version = sh("node -pe 'require(\"../../node_modules/react-native/package.json\").version'")
    ENV["HERMES_ENGINE_TARBALL_PATH"] = "#{Dir.pwd}/hermes-runtime-darwin-v#{react_native_version}.tar.gz"
    cocoapods
  end

  lane :build do
    react_native_version = sh("node -pe 'require(\"../../node_modules/react-native/package.json\").version'")
    ENV["CI"] = "true"
    ENV["HERMES_ENGINE_TARBALL_PATH"] = "#{Dir.pwd}/hermes-runtime-darwin-v#{react_native_version}.tar.gz"
    cocoapods
  end

  lane :gofir do
    gym(
      workspace: "SDHotelDataInsightApp.xcworkspace", 
      scheme: "SDHotelDataInsightApp(Production)",
      include_bitcode: false,
      include_symbols: false,
      silent: true,
      clean: true,
      export_method: "development",   # Available options: app-store ad-hoc package enterprise development
    )
    fir_cli(
      api_token: "ae1d65e6383eeb50b2723f85b5e30b2b",
      changelog: "release a new version",
      specify_file_path: lane_context[SharedValues::IPA_OUTPUT_PATH],
    )
  end

  lane :publish do
    podrelease
    gofir
  end
end
